version: "3.8"
services:
  bind:
    image: bind
    build:
      context: bind
    volumes:
      - ${DPSRV_MNT}/etc/bind/named.conf:/etc/bind/named.conf
      - ${DPSRV_MNT}/etc/bind/named.conf.options:/etc/bind/named.conf.options
      - ${DPSRV_MNT}/etc/bind/named.conf.zones:/etc/bind/named.conf.zones
      - ${DPSRV_MNT}/etc/bind/zones:/var/bind/zones
