version: "3.8"
services:
  bind:
    build:
      context: bind
    environment:
      GIT_BIND_RC_REPO: "https://github.com/dpsrv/rc-bind"
    volumes:
      - /root/.config/git:/root/.config/git
      - /vagrant/rc/etc/bind/named.conf:/etc/bind/named.conf
      - /vagrant/rc/etc/bind/named.conf.options:/etc/bind/named.conf.options
      - /vagrant/rc/etc/bind/named.conf.zones:/etc/bind/named.conf.zones
      - /vagrant/secrets/etc/bind/zones:/var/bind/zones
    restart: unless-stopped
  hadoop:
    build:
      context: hadoop
    cap_add:
      - SYS_ADMIN
    environment:
      container: docker
    ports:
      - "2322:22"
      - "29000:9000"
      - "29868:9868"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /vagrant:/vagrant
